alias: Verisure log external changes
mode: queued
trigger:
  - platform: state
    entity_id: binary_sensor.my_verisure_alarm_external
action:
  - service: logbook.log
    data:
      name: Verisure
      message: External perimeter changed
