alias: Verisure refresh on HA start
mode: single
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      seconds: 30
  - service: my_verisure.get_status
    data:
      installation_id: INSTALLATION_ID
