alias: Verisure internal total armed notify
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.my_verisure_alarm_internal_total
    to: "on"
action:
  - service: notify.persistent_notification
    data:
      title: Verisure
      message: Internal total is ON
